### ISSUE TITLE
Graphpad prism v8

### ISSUE THREAD

**Issue by JamesYates** [Yue-Jiang/pzfx#8]
I've tried to read tables from graphpad prism version 8 using pzfx. I get and error that suggests the xml isn't interpretable. If I export the tables from prism into xml format then all is fine. Is there a fix for this?

Error in doc_parse_file(con, encoding = encoding, as_html = as_html, options = options) : 
  Start tag expected, '<' not found [4]

**Comment by Yue-Jiang** [comment]
Hi! Thanks for reporting. I suspect it's more nuanced than an issue with version 8, since I just created a small file with 8.4.3 and it imports fine. Would you be able to share a small example file that fails to import to help me trouble shoot? Can email me privately if you don't want to attach it here.

**Comment by JamesYates** [comment]
Hello

Thanks for the prompt reply

Attached is an example file based upon the one I was having issues with. I have checked and it won’t import into R

Regards

James

**Comment by Yue-Jiang** [comment]
Looking at the file you sent me, I suspect it's not a valid .pzfx file, but rather a .pzf file, even though the file extension suggests otherwise. .pzf is an older version of GraphPad Prism output format, which is not XML hence not really parsable, causing the error. However, the file can be opened with GraphPad Prism 8.4.3, and when I save it as .pzfx I'm able to import it into R using `read_pzfx()`.

**Comment by Yue-Jiang** [comment]
This doc contains more info on the XML specification of .pzfx format. This R package assumes the input .pzfx file follows these specifications. https://www.graphpad.com/support/faq/prism-integrated-saves-prism-files-instruments/

**Comment by JamesYates** [comment]
Hello

So simple! Thanks for looking into this

James
